# nginx.conf
events {}

http {
    server {
        listen 80;
        location / {
            return 200 'Bank Services: /internet /mobile /insurance /loan';
        }

        location /internet/ {
            proxy_pass http://internetbanking:80/;
        }

        location /mobile/ {
            proxy_pass http://mobilebanking:80/;
        }

        location /insurance/ {
            proxy_pass http://insurance:80/;
        }

        location /loan/ {
            proxy_pass http://loan:80/;
        }
    }
}
